{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "collectorforkubernetes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "collectorforkubernetes.fullname" . }}
rules:
  - apiGroups:
    - ""
    - apps
    - batch
    - extensions
    resources:
    - cronjobs
    - daemonsets
    - deployments
    - jobs
    - nodes
    - pods
    - replicasets
    - replicationcontrollers
    - scheduledjobs
    - statefulsets
    verbs:
    - get
    - list
    - watch
{{- end -}}
